### ISSUE TITLE
broken in 2021.3.0f1 

### ISSUE THREAD

**Issue by shntat** [VisualPinball/VisualPinball.Engine.Mpf#12]
Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfExtensions.cs(27,21): error CS1729: 'GamelogicEngineSwitch' does not contain a constructor that takes 2 arguments

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfGamelogicEngine.cs(72,28): error CS1061: 'GamelogicEngineSwitch' does not contain a definition for 'InternalId' and no accessible extension method 'InternalId' accepting a first argument of type 'GamelogicEngineSwitch' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfGamelogicEngine.cs(73,21): error CS1061: 'GamelogicEngineSwitch' does not contain a definition for 'InternalId' and no accessible extension method 'InternalId' accepting a first argument of type 'GamelogicEngineSwitch' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfGamelogicEngine.cs(77,21): error CS1061: 'GamelogicEngineCoil' does not contain a definition for 'InternalId' and no accessible extension method 'InternalId' accepting a first argument of type 'GamelogicEngineCoil' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfGamelogicEngine.cs(81,21): error CS1061: 'GamelogicEngineLamp' does not contain a definition for 'InternalId' and no accessible extension method 'InternalId' accepting a first argument of type 'GamelogicEngineLamp' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfExtensions.cs(69,23): error CS1729: 'GamelogicEngineCoil' does not contain a constructor that takes 2 arguments

Library\PackageCache\org.visualpinball.engine.missionpinball@0.0.1-preview.14\Runtime\MpfExtensions.cs(106,41): error CS1729: 'GamelogicEngineLamp' does not contain a constructor that takes 2 arguments

![Screenshot 2022-05-30 033619](https://user-images.githubusercontent.com/12681995/170975007-1d189bee-0447-4e1c-9fef-82e166d4b852.png)

**Comment by shntat** [comment]
Ok I will let you know if it works after a clean unity install.   thanks

**Comment by shntat** [comment]
Yay I can get back to work.

**Comment by freezy** [comment]
Out of curiosity, are you building a table in VPE using MPF?

**Comment by shntat** [comment]
I have not been able to get that far yet with the other issues i have been having.

**Comment by freezy** [comment]
How are you planning to do the game logic? Reprogram everything by hand?

**Comment by shntat** [comment]
I have a lot of work ahead of me.  The main issues i have is not being able to use drag points yet. I have to use vpx to use drag points for now to design parts then import. Also when importing  from vpx the trough does not import and the plunger does not work yet.

So right now i am still designing my table and extracting assets so i can build game logic for the 1360 x768 color screen.

**Comment by shntat** [comment]
I finally have drag points that work. I toggled off and on the 3d icon option on the gizmo pop out menu and they showed up.

**Comment by freezy** [comment]
Yes, the gizmos must be enabled in order for the drag points to show up.

**Comment by shntat** [comment]
i had gizmos on from the start but the icons covered the table so i had to turn them off that's why i have said the drag points did not work. So i decided to play with the gizmo settings on the scene window and saw that the drag points started to work after i toggled the 3d icons option in the screenshot. It was a weird find.

![Screenshot (1)](https://user-images.githubusercontent.com/12681995/171214958-2f29b834-609f-47b8-b228-2e6c52657b55.png)

**Comment by freezy** [comment]
You can also turn off all the VPE gizmos through the *Visual Pinball* menu (*Editor -> Disable Gizmos* or similar). Like that you can keep the less intrusive Unity gizmos, have the drag points and other helpers working, with a minimal overhead in the scene.

**Comment by shntat** [comment]
any idea on why the trough and plunger don't import properly working?
I created a new blank table in vpx and tried to import and only the flippers work.

**Comment by freezy** [comment]
No, but to be honest I haven't looked at importing a blank table for some time now, so some things might have broken.

I'll try to check tonight.
